### ISSUE TITLE
Quite confused with the process

### ISSUE THREAD

**Issue by moyoujun** [puleos/object-hash#105]
compared to js-sha1, the result is different, but i dont know how to fix with that:
```javascript        
    let testString = "Mary has a little lamb";
    let base64String = btoa(String.fromCharCode(...new Uint8Array(sha1.array(testString))));
    console.log(base64String);
 ```
 and below is object-hash:
```javascript        
   let base64String = hash(testString, {algorithm: 'sha1', encoding:"base64"});
   console.log(base64String);
```
But the result is different, here is the result:

>     js-sha1: 5mz2bBoctVpzM49f3oO/GIQKwsI=
>     object-hash: ykFp5cj0mcBf+Zfk1Ej6kAtc8tM=

And I also test with C#,  below is my c# code:
```csharp		
string source = "Mary has a little lamb";
byte[] sourceBuffer = System.Text.Encoding.UTF8.GetBytes(source);
var sha1 = new System.Security.Cryptography.SHA1CryptoServiceProvider();
byte[] hashedBuffer = sha1.ComputeHash(sourceBuffer);
Console.WriteLine(Convert.ToBase64String(hashedBuffer));
```
I got the same result with js-sha1,  maybe someone here can tell me why, and how can i fix it.

Thanks a lot!

**Comment by addaleax** [comment]
See #104 – this library hashes JS values *as JS values*, not strings as byte sequences. There is no way to give the same output as standard hashing functions. If you need that, you could use any other hashing library.
