### ISSUE TITLE
Add algorithm 'none' for easy debugging.

### ISSUE THREAD

**Issue by MasterEric** [puleos/object-hash#106]
Currently, when I want to debug to see what the string that would be hashed is, I have to run the following:

```
let output = '';
require('object-hash').writeToStream(input, options, {
  write: (x) => {
    output += x;
  },
});
return output;
```

It would be convenient if, when the hashing algorithm requested is `none` or some other placeholder value, the library would simply output the value that would be hashed.

**Comment by addaleax** [comment]
PRs are welcome :)

**Comment by MasterEric** [comment]
Hey, so it appears this feature already existed, named `passthrough` rather than `none`.

I didn't realize it existed since it is completely absent from the documentation, and only found it after inspecting the code. I just made pull request #107, which revises the documentation to inform users about the feature.

**Comment by addaleax** [comment]
Thanks for the PR!
