### ISSUE TITLE
Javascript unsigned / signed typed arrays return the same hash

### ISSUE THREAD

**Issue by ArtiomTr** [puleos/object-hash#113]
Thank you for maintaining such great library.

I was looking at the source code and saw a small typo:
https://github.com/puleos/object-hash/blob/5e82c257251ab213bbd77a0f742d34c464af56cd/index.js#L350-L353
Int8Array has an `uint8array` prefix. The same is for the [Int16Array](https://github.com/puleos/object-hash/blob/5e82c257251ab213bbd77a0f742d34c464af56cd/index.js#L359) and [Int32Array](https://github.com/puleos/object-hash/blob/5e82c257251ab213bbd77a0f742d34c464af56cd/index.js#L367).

This typo leads to the behavior, that different arrays return the same hash. I've reproduced this behavior in [codesandbox](https://codesandbox.io/s/restless-cloud-d4e0x7?file=/src/index.js).

Is it a bug or intended behavior? Thank you in advance.

**Comment by addaleax** [comment]
Yet, it’s a bug. Feel free to open a PR for this :+1:
