### ISSUE TITLE
Snapshot tests

### ISSUE THREAD

**Issue by ArtiomTr** [puleos/object-hash#115]
Jest provides awesome feature - [snapshot testing](https://jestjs.io/docs/snapshot-testing). These tests can help automate versioning - according to the documentation, changes that affect hash values are considered `semver-major`. So theoretically, with these tests, some pipeline could automatically bump version when any of snapshot files change.

However, according to the jest's [package.json file](https://github.com/facebook/jest/blob/7d4595eb935556b8214e1dda45b0b68dfc67068f/packages/jest/package.json#L30), it supports only node versions `12.x`, `14.x`, `16.x` and `>= 17.x`. So this means that these additional checks require either dropping support of older node versions, or having two different testing frameworks - mocha (current) and jest (for snapshots).

If you decide to add them, I could open a PR.

**Comment by jonkoops** [comment]
I don't see a good reason to introduce snapshot testing here. This library takes a set of inputs and expects an output of a given value, this is already perfectly covered by the unit tests, so adding snapshots would not really be of value.
