### ISSUE TITLE
Changelog for v3

### ISSUE THREAD

**Issue by kachkaev** [puleos/object-hash#116]
👋 This issue is a new instance of https://github.com/puleos/object-hash/issues/87. v3.0.0 was released recently but [README → Changelog](https://github.com/puleos/object-hash#changelog) only mentions 2.0.0:

<img width="876" alt="Screenshot 2022-02-21 at 09 47 28" src="https://user-images.githubusercontent.com/608862/154930368-fa390af3-e527-44f7-be36-576db86f07da.png">

Although it is possible to look at git log and find https://github.com/puleos/object-hash/pull/114, it is probably too much of a detour for such a popular library 🙂

<a href="https://www.npmjs.com/package/object-hash"><img width="380" alt="Screenshot 2022-02-21 at 09 50 53" src="https://user-images.githubusercontent.com/608862/154930666-bc46ddf4-38c8-472b-ae28-d191191d2356.png"></a>

**Comment by dieseldjango** [comment]
Does v3 break compatibility with hashes?

**Comment by addaleax** [comment]
Yes, v3.x generates different hashes but is otherwise compatible.

Feel free to open a PR.

**Comment by JaLe29** [comment]
@addaleax can you please explain what do you mean by "different hashes"?

```
// V2
hash({foo: 'bar'}) // => '67b69634f9880a282c14a0f0cb7ba20cf5d677e9'

// V3
hash({foo: 'bar'}) // => 'diferent hash' ????????????
```

So, sha1 in v2 is not same in v3?

**Comment by dwelle** [comment]
@JaLe29 check https://github.com/puleos/object-hash/pull/114 — previous version wasn't distinguishing between typed arrays

**Comment by medikoo** [comment]
It's better not to release a breaking change than to release it with zero (changelog) documentation.
