### ISSUE TITLE
cannot specify supported algorithms beyond sha1/md5 after node upgrade

### ISSUE THREAD

**Issue by jrwashburn** [puleos/object-hash#119]
Similar to #109 after a node upgrade, compiler will not allow specification of sha256 (for example.)  

TSError: ⨯ Unable to compile TypeScript:
src/core/transaction/TS.ts:16:67 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(object: {} | null, options?: NormalOption | undefined): string', gave the following error.
    Type '"sha256"' is not assignable to type '"sha1" | "md5" | "passthrough" | undefined'.
  Overload 2 of 2, '(object: {} | null, options?: WithBufferOption | undefined): Buffer', gave the following error.
    Type '"sha256"' is not assignable to type '"sha1" | "md5" | "passthrough" | undefined'.

16         const calculatedHash = hash(myobj, { algorithm: 'sha256' });

**Comment by addaleax** [comment]
It seems like you’re using the typescript definitions from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/object-hash/index.d.ts which is not part of this project. You may want to raise this issue in that repository, or, more directly, update the type definitions with a pull request directly.
