### ISSUE TITLE
Use as a key-value store

### ISSUE THREAD

**Issue by iffsid** [puleos/object-hash#16]
Would it be possible to add support to use the hashing as the middle-man for a key-value store?
As I see it, this would mean adding two more methods to `HashTable`, namely `set(key, value)` and `get(key)`, where the `key` is hashed. This would be particularly useful in cases when a key-value store is needed for unwieldy keys (like large `Objects`, `Arrays`, even perhaps `Canvas images`(?), where stringifying would make things difficult).

**Comment by addaleax** [comment]
Maybe it’s worth noting that the naming of `HashTable` is somewhat confusing (at least, it pretty much was for me when I first had a look at this library):
While it is internally using a “real” hash table, it currently implements the API of something which is called `HashSet` (or similar) in other languages and implementations, and there is no `HashMap`-like structure in this library right now (like the name `HashTable` led me to expect).

**Comment by iffsid** [comment]
That is true; what's termed `HashTable` is indeed closer in spirit to a `HashSet`.
The question still remains though, if it would be possible (even acceptable) to implement a `HashMap` since most of the plumbing is already present (tantalisingly!) to enable it.

**Comment by CamiloMM** [comment]
Just my 2 cents, but I don't even see why there's a HashSet implementation here, and personally think in an environment like `npm` the Unix philosophy of "do one thing and do it well" should be taken to the (pretty moderate) extreme of "just go and code another module for a HashMap".

I mean, if you `npm install object-hash`, why should it come with a key-value store? Especially from a browserify-able point of view.

**Comment by puleos** [comment]
@addaleax I agree that the naming of the hash table is poorly conceived.  This design grew out of a specific use case that I had at the time.  In hindsight it would be been a better idea to keep the implementation of hashTable separate as @CamiloMM suggested.  @iffsid since HashTable is already in the api I would be open to merging in a patch with the signature you suggested.
