### ISSUE TITLE
How to use this in the browser?

### ISSUE THREAD

**Issue by episodeyang** [puleos/object-hash#17]
I included the source in the html, but the object-hash object is not exposed at a global variable.

Do I have to use browserify?

Thanks!

**Comment by episodeyang** [comment]
LOL I used the 
```bash
gulp dist
```

and imported the generated file. but I still don't see the object hash constructor in the global scope!! Have spent an hour on this already.

**Comment by episodeyang** [comment]
Hi @addaleax and @puleos 
I tried other libraries and this one seems the more reliable object hash implementation. Please advice!

**Comment by CamiloMM** [comment]
I didn't write this lib so my word certainly isn't final, but I checked and the js file in `/dist` doesn't seem to set *any* global variable, so probably you'd indeed have to use it via browserify, which anyway is super neat and lets you keep libs up-to-date with `npm`.

Still, in that case I'm not sure why there'd be a separate "browser version" of the lib.

**Comment by puleos** [comment]
@episodeyang sorry for the delay.  I did not include the standalone option in my build script.  This was an oversight!  I just pushed a new version 3c0c86745e09dd22a6bfa68b590b2f34a1d467b4 of the project with an updated dist.  You will now be able to reference window.objectHash in the browser.

**Comment by episodeyang** [comment]
@puleos Thank you! 
So now I can just do `gulp dist`? 
Best, Ge

**Comment by puleos** [comment]
@episodeyang yes!
