### ISSUE TITLE
Bug with unicode character '\u00A0'

### ISSUE THREAD

**Issue by episodeyang** [puleos/object-hash#18]
I run into this funny bug in development today.

If you just do `objectHash('\u00A0')` on node.js and in Chrome, the result is different.

In Chrome, the result is 
```javascript
>> objectHash('\u00A0')
"5edfeb46a3483b6b841f805756bc873ede319bee"
>> objectHash(' ')
"5edfeb46a3483b6b841f805756bc873ede319bee"
>> ' '.charCodeAt()
160
```

However, if you do the same in node.js, the result is different:

```javascript
> objectHash('\u00A0')
'e97acbee3eb51eca346c892acc0b7c27b0bb6528'
> objectHash(' ')
'e97acbee3eb51eca346c892acc0b7c27b0bb6528'
> ' '.charCodeAt()
160
```

We are using the objectHash function to check agreement between the server copy and the client copy. It is absolutely crucial that the two gives the same result. Do you think this is a problem with crypto, or with `objectHash` itself?

Please advice!

**Comment by addaleax** [comment]
This is mostly a problem with the fact that this module uses an outdated approach to browserify, i.e. the no longer maintained `gulp-browserify` module. The `crypto` API exposed by version of `crypto-browserify` that comes with `gulp-browserify` is outdated and handles non-ASCII strings in a way different from both current Node.js `crypto` and current `crypto-browserify`.

I think the browser behaviour here is correct (i.e. implicit conversion to `utf-8` before hashing). I can submit a PR to fix this in Node.js later, but I don’t really have the time to look into how to update the build process in a way that uses only up-to-date modules.

**Comment by episodeyang** [comment]
Thanks @Addaleax!

Yes the PR will be very much appreciated!! if it is the browser behaviour that is correct, then why does the node.js version make the mistake even though it is not using the browserified code?

I am thinking about adding a crypto in the dependency in the package.json. Do you think that will fix the node.js version?

**Comment by addaleax** [comment]
You should be able to get the correct (or, at least, consistent) behaviour by pointing to my changes (i.e. use git+https://github.com/addaleax/object-hash.git#hash-encoding as the version string in the package.json until this is fixed in this repository).

The problem here was that the default `binary` encoding for hashes in Node.js tries to map all characters to single bytes, and does not perform proper encoding. (e.g. the characters U+03C3 and U+01C3 both get mapped to 0xc3 and therefore produced the same hash).
Since the crypto-browserify behaviour already is converting to UTF-8 and I think that that’s the best choice in general, my PR makes it the standard behaviour.

**Comment by addaleax** [comment]
And btw, you might rather thank @puleos for this library, but it seems he is not too active anymore…

**Comment by episodeyang** [comment]
Thanks @addaleax (and @puleos for this library!)

I was just about to push a fix to my own fork and you beat me to it:) the #hash-encoding branch fixes the problem!

In terms of the browerify, my app needs the object to be exposed globally after browserify. Would it be okay to add a line in the library that looks like:

```javascript
if (window) window.objectHash = objectHash;
```
If this is not favorable, I can also just do this on my own fork.

Thanks again!!

**Comment by addaleax** [comment]
I would not count too much on a fast response from @puleos to merge this in here (at least the last time I made a PR it was about a month), so maybe for now you are better off merging my hash-encoding branch into your fork and adding your line for global exposure there…

**Comment by episodeyang** [comment]
Got it! I will do that!

**Comment by puleos** [comment]
Granted @addaleax push access.

**Comment by addaleax** [comment]
@puleos Thanks, I’ll do my best to help – If you want to add me for npm, my username there is sqrt
