### ISSUE TITLE
type Blob Management

### ISSUE THREAD

**Issue by ronyrun** [puleos/object-hash#26]
Hello, 

I have some object with a blob as property.

WHen trying to hash, I have this issue : 

![image](https://cloud.githubusercontent.com/assets/7273443/11931931/d4bf51da-a7f1-11e5-9e4e-03571cd75c28.png)

![image](https://cloud.githubusercontent.com/assets/7273443/11931995/52a4b7c0-a7f2-11e5-88dc-d94602949db8.png)

What about only take the size and  the type and the digest of the blob for the hash process ?
Or convert the blob in the process... I don't know.

**Comment by addaleax** [comment]
Sorry, but this one is a little bit harder – As far as I can tell, `blob.digest` is non-standard (in fact, neither my installed FF version nor my installed Chrome version support it, and I can find nothing about it in the [specs](https://w3c.github.io/FileAPI/#constructorBlob)?)

The only reliable way, as far as I can tell, would be to use a FileReader, but that’s async and this library has, so far, only supported objects which can be stringified synchronously, i.e. it would be a pretty big change to modify this behaviour.

I’m open for ideas, but I don’t see any easy way to do this.

**Comment by ronyrun** [comment]
Hi,
Yes I understand,

I'm not an expert concerning the blob.digest.
What about to remove this blob from the object in order to get a hash without an error ?

**Comment by addaleax** [comment]
Maybe one could do something like specifying a replacement/filter function that would remove Blobs (similar to e.g. [`JSON.stringify(value, replacer)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)… I guess that would be a good idea anyway, will look into that later today :)

**Comment by ronyrun** [comment]
Thank you Anna :)

I'm using your lib in order to control if No Sql Docs exist or not during a Synchronization between Databases.

**Comment by addaleax** [comment]
Sorry, I probably won’t come to fix this until after the 24th :/

**Comment by addaleax** [comment]
Sounds like a cool project! Hope these issues here are not blocking your work too much

**Comment by ronyrun** [comment]
No worries :) I love your lib !

**Comment by addaleax** [comment]
So, I got to take a look at this – It does not seem feasible to hash Blob contents at the moment, but in your special case that should not be a problem. You can specify either the `.ignoreUnknown` option which makes object-hash ignore Blobs (and other types it does not know how to handle), or, more specifically, remove only `Blob` objects by specifying a `.replacer` function:

```js
hash(..., {
  replacer: function(value) {
    if (value instanceof Blob) {
      return value.size;
    }
    
    return value;
  }
});
```

This will be just fine, since your data already contains a digest of the contents, generated by an external library.

You need to upgrade to version 1.0.0 of this library to take advantage of this feature :)

**Comment by ronyrun** [comment]
Thank you !! the replacer is exactly what I needed ! this way I can manage what I have :)

**Comment by addaleax** [comment]
Great! Let me know when there’s another issue :)

**Comment by ronyrun** [comment]
OK!

**Comment by un33k** [comment]
For those who use `object-hash` as a cache key generator, please note that an invalid cache is better than a stale cache.
If so, and to force cache invalidation on objects that `may` include blobs (e.g. HTTP calls), just return a unique value to force cache invalidation. 

```typespcrit
return hash(someDataObject, {
 replacer: (value) => (value instanceof Blob ? uuidV4() : value),
});
```

**Comment by un33k** [comment]
Also, if we add `async/await to the `replacer` function signatures, we can easily call async functions in a sync manner. 

```
const blobToBase64 = (blob) => {
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.readAsDataURL(blob);
    reader.onloadend = function () {
      resolve(reader.result);
    };
  });
};


// something like this, but implemented at the library level
 replacer: async (value) => (value instanceof Blob ? await blobToBase64(blob) : value),
```
