### ISSUE TITLE
Is it possible to return decrypt?? 

### ISSUE THREAD

**Issue by ycpatel813** [puleos/object-hash#33]
Hi 
I want to use it to generate access key which is publicly shared to my client when my client request using that key i can return decrypt that key and get actual result.is it possible in this ?? or any suggestion or idea to tackle this situation.

**Comment by addaleax** [comment]
I’m not a 100 % sure what you want to do, but I can’t really see how this issue is related to `object-hash` specifically. If you’re seeking a way to serialize and deserialize objects again, then no, that is unfortunately not something that’s supported by this library.

**Comment by ycpatel813** [comment]
@addaleax thanks for reply you are totally right.sorry for not using technical language.

**Comment by addaleax** [comment]
No problem, I was just not sure what exactly you were asking. Let me know if there’s anything else I can help with!

**Comment by ycpatel813** [comment]
Hello sir,
       Actually i am developing Project Management tool for our client in that Admin can create unlimited project.I want to generate Personal Access Tokens for every project with their scope so Admin gives Personal Access Tokens to user and user uses it to write their API detail for their project only.if token has only reading scope then user can not write API detail.simple and straightforward.Simply i can say Github Personal Access token.:smile:
