### ISSUE TITLE
Object-hash leaking?

### ISSUE THREAD

**Issue by d4vidi** [puleos/object-hash#39]
Hello,
suspecting memory leaks, I ran the following test over object-hash:
```javascript
const hash = require('object-hash');
console.log(process.memoryUsage());
while (true) {
  const pre = Date.now();
  for (let i = 0; i < 1000; i++) hash(data);
  const post = Date.now();
  console.log(process.memoryUsage(), "runtime: "+(post-pre)+"ms");
}
```

These were the results:
```
{ rss: 21213184, heapTotal: 10522624, heapUsed: 4672656 }
{ rss: 85860352, heapTotal: 70365184, heapUsed: 38203144 } 'runtime: 329ms'
{ rss: 118218752, heapTotal: 102469632, heapUsed: 79757256 } 'runtime: 325ms'
{ rss: 151285760, heapTotal: 135122944, heapUsed: 112984104 } 'runtime: 443ms'
{ rss: 178872320, heapTotal: 161873920, heapUsed: 126826120 } 'runtime: 513ms'
{ rss: 206196736, heapTotal: 189136896, heapUsed: 165380888 } 'runtime: 553ms'
{ rss: 244736000, heapTotal: 227192832, heapUsed: 189656008 } 'runtime: 664ms'
{ rss: 272257024, heapTotal: 254455808, heapUsed: 224160496 } 'runtime: 738ms'
{ rss: 315011072, heapTotal: 297373696, heapUsed: 263990928 } 'runtime: 812ms'
{ rss: 342827008, heapTotal: 325685248, heapUsed: 294446712 } 'runtime: 885ms'
{ rss: 370958336, heapTotal: 352948224, heapUsed: 315126088 } 'runtime: 991ms'
{ rss: 399020032, heapTotal: 381259776, heapUsed: 341713960 } 'runtime: 1107ms'
{ rss: 412856320, heapTotal: 395227136, heapUsed: 362916912 } 'runtime: 1422ms'
{ rss: 440881152, heapTotal: 422490112, heapUsed: 384875336 } 'runtime: 1213ms'
{ rss: 468836352, heapTotal: 450801664, heapUsed: 412514440 } 'runtime: 1328ms'
{ rss: 496558080, heapTotal: 478064640, heapUsed: 445826144 } 'runtime: 1412ms'
{ rss: 525045760, heapTotal: 506376192, heapUsed: 469118536 } 'runtime: 1499ms'
{ rss: 553041920, heapTotal: 533639168, heapUsed: 498784816 } 'runtime: 1632ms'
{ rss: 613945344, heapTotal: 594788352, heapUsed: 550526600 } 'runtime: 1754ms'
{ rss: 641900544, heapTotal: 623099904, heapUsed: 575188672 } 'runtime: 1862ms'
{ rss: 669708288, heapTotal: 650362880, heapUsed: 605594576 } 'runtime: 1967ms'
{ rss: 697405440, heapTotal: 677625856, heapUsed: 641817448 } 'runtime: 2096ms'
^C
```

Seems like the there are serious leak issues. Could you advise?
Do note that I've tried all versions 1.1.0 - 1.1.4 (inclusive).

Thanks.

**Comment by addaleax** [comment]
I’ll try to look into this. Can you provide a full reproduction, ideally with your `data` object or an approximation to it?

I can confirm the increasing run times but not the leak itself.

**Comment by d4vidi** [comment]
Sure. `data` is in fact a gibberish object that I created:
```
const data = {
  data_arr: [
    {
      name: "wegierngheirh",
      desc: "wergiojwegho",
      phone: 3253246346
    },
    {
      name: "Weg24g24",
      desc: "r0-u3-t23t",
      phone: 1111
    }
  ],
  globalValue: 124135,
  moreContent: {
    withSubStuff: "wet9h23t92-23t-23t0=gj243g0j"
  }
}
```

**But it is really irrelevant:** This problem will also be introduced even if you set `data={}`

**Comment by addaleax** [comment]
> **But it is really irrelevant:** This problem will also be introduced even if you set `data={}`

I am still not so sure about the memory leak – inserting a `gc();` call after the loop and running the test script with `--expose-gc` seems to keep the resource usage pretty stable.

The timing thing seems to only occur on Node >= 6.3.0, so I’ll dig into that.

**Comment by addaleax** [comment]
So, yeah, this comes from nodejs/node@2c7804ad9eedad7f5e996a06af4c59f8a4bd7103 but in a way that’s not really to blame on Node itself. I’ll have a patch up for object-hash in no time.

**Comment by addaleax** [comment]
`+ object-hash@1.1.5`

It would be great if you could confirm that everything works as expected now. :)

**Comment by d4vidi** [comment]
Amazing! Thanks for this super-fast round-trip. I'll look into it ASAP.
Just to be sure -- the fix has no effect on the resulting hash codes, right?

**Comment by addaleax** [comment]
> Just to be sure -- the fix has no effect on the resulting hash codes, right?

Yes, exactly. :)

**Comment by d4vidi** [comment]
Double & triple tested, seems good. Can't thank you enough!

**Comment by addaleax** [comment]
My pleasure! :smile:
