### ISSUE TITLE
Problem with pre-built javascript as main file

### ISSUE THREAD

**Issue by tomasztomys** [puleos/object-hash#44]
![image](https://cloud.githubusercontent.com/assets/7750691/23454909/1c4d3e9e-fe6e-11e6-8f77-5eacdf4acf65.png)

**Comment by isnifer** [comment]
@addaleax you are using 'crypto' as dependency. But you didn't add it into `dependencies` section in package.json. It will help too.

**Comment by addaleax** [comment]
Added `v1.1.7` with a `browser:` field instead of a `main:` field pointing to the browser file, that seems like the better approach.

> you are using 'crypto' as dependency. But you didn't add it into `dependencies` section in package.json. It will help too.

The `crypto` module on npm is definitely nothing that should ever appear as a dependency, it’s not the same as Node’s built-in `crypto` module or `browserify-crypto`.

**Comment by tomasztomys** [comment]
The problem still appears...
![image](https://cloud.githubusercontent.com/assets/7750691/24701178/d03b8cfc-19f9-11e7-946c-c479646893f9.png)

**Comment by addaleax** [comment]
@tomasztomys Can you answer to https://github.com/puleos/object-hash/issues/44#issuecomment-283363376?

**Comment by tomasztomys** [comment]
Yes, it helps, but it's not a solution :). It's not natural import :)

**Comment by addaleax** [comment]
@tomasztomys Yes, but also, by “Could you let me know how/in what context this occurs?” I meant … are you using some kind of build system, or generally, *how* do you load the module?

**Comment by tomasztomys** [comment]
I use webpack v1 and import by: ` import objectHash from 'object-hash'; `

**Comment by kwanray** [comment]
I am using 1.1.8 and webpack 1.12.14 with react. I am using it as `const hash = require('object-hash')` in one of the Javascript file.
