### ISSUE TITLE
Similar Hash for Anonymous Functions

### ISSUE THREAD

**Issue by EmpireWorld** [puleos/object-hash#46]
When i try the below code:
```javascript
const hash = require("object-hash");
console.log(hash(function () {})); // Output: 4122c3af912b486962725f2aadb66af50ada646d
console.log(hash(function () {})); // Output: 4122c3af912b486962725f2aadb66af50ada646d
```
Outputs are same.

**Comment by addaleax** [comment]
Right, the code uses `.toString()` to hash functions. What would your expected output be?

I don’t think `object-hash` has reliable means of turning object identity into hashable information, so even if you expect different hashes it might not be feasible to generate those. :/

**Comment by EmpireWorld** [comment]
I want to generate hash for functions to store them identically for example:
```
const exampleHash = require("example-hash");
let functionsContainer = {};

// This should be sample
function sample () {}
functionsContainer[ exampleHash(sample) ] = sample;
functionsContainer[ exampleHash(sample) ] = sample;

// This should be difference
let anon1 = function () {}
functionsContainer[ exampleHash(anon1 ) ] = anon1;
let anon2 = function () {}
functionsContainer[ exampleHash(anon2 ) ] = anon2;
```

**Comment by EmpireWorld** [comment]
Please visit the below address and check the "_wp_filter_build_unique_id" function.
[https://github.com/WordPress/WordPress/blob/master/wp-includes/plugin.php#L874](https://github.com/WordPress/WordPress/blob/master/wp-includes/plugin.php#L874)

**Comment by EmpireWorld** [comment]
Thanks. i get wrong. excuse me.

**Comment by addaleax** [comment]
@EmpireWorld No problem. It would be possible to implement what Wordpress does there, but I’m really not sure how I’d feel about adding hidden properties to the function objects – if you think this is important, I can still look into it as an optional feature.

**Comment by EmpireWorld** [comment]
No there is no worry. i used the below answer:
[http://stackoverflow.com/questions/1997661/unique-object-identifier-in-javascript](http://stackoverflow.com/questions/1997661/unique-object-identifier-in-javascript)
