### ISSUE TITLE
Different hash with the same object (but without the same attribute order)

### ISSUE THREAD

**Issue by henricazottes** [puleos/object-hash#55]
Hi,
Just for the records, I had an issue when hashing two "same" objects. It appeared that an object order its attributes in the order they are added to it. Moreover, this hash() function will vary depending on the attribute order. It means that my two "same" objects (containing the same attributes and values) where giving a different hash.

My solution to this was to use ``Object.entries(myObject).sort()`` like this:
``` javascript
// Two objects containing the same data, but differents by construction
let toto = {a: 1, b: 2};
let titi = {b: 2, a: 1};

// End up with a different hash output
console.log(hash(toto)); // AAAAAA
console.log(hash(titi)); // BBBBBB

// Let sort the attributes
toto = Object.entries(toto).sort(); // [[a, 1],[b,2]]
titi = Object.entries(titi).sort(); // [[a, 1],[b,2]]

// Same output ! :D
console.log(hash(toto)) // CCCCCC
console.log(hash(titi)) // CCCCCC
```

**Comment by addaleax** [comment]
@henricazottes Can you check which version of object-hash you are using? This has been fixed a long long time ago, I think…

**Comment by bhupendraparihar** [comment]
Version 1.2.0 is still having the same issue.

**Comment by addaleax** [comment]
Closing due to lack of follow-up, please let me know if that is mistaken

**Comment by henricazottes** [comment]
I don't know why I had the version 1.1.8 installed. I tried with version 1.2 and it seems to work fine (at least with simple objects. Didn't try with nested ones).
