### ISSUE TITLE
Link to https://github.com/bean5/node-object-hash in README

### ISSUE THREAD

**Issue by bean5** [puleos/object-hash#58]
As we agreed upon in https://github.com/puleos/object-hash/pull/52, I have separated the project that wraps object-hash in a node docker container. You mentioned that you'd like to link to the project. I proposed some verbiage at https://github.com/puleos/object-hash/pull/57. Feel free to modify!

**Comment by jonkoops** [comment]
The related PR has been merged, so I will consider this resolved.

**Comment by bean5** [comment]
Oh. Nice.
