### ISSUE TITLE
Not working in angular2

### ISSUE THREAD

**Issue by maelfosso** [puleos/object-hash#59]
Hi,

Please how to use it on angular 2 ?
The code ``` import {hash} from "object-hash" ``` trigger an error

**Comment by addaleax** [comment]
@maelfosso Can you post that error here somewhere?

**Comment by maelfosso** [comment]
@addaleax  Have already solve the problem. It was because ```hash``` it's not between the method to import from ```object-hash```

**Comment by Karankang007** [comment]
Is https://www.npmjs.com/package/@types/object-hash updates with this fix?

**Comment by Karankang007** [comment]
This works for me:

```
// Import
import * as Hash from 'object-hash';

// Usage
const argHash = Hash(args);
```
