### ISSUE TITLE
Support option to not sort object keys.

### ISSUE THREAD

**Issue by mkrause** [puleos/object-hash#65]
Currently, all objects are sorted before hashing. This makes sense, as objects are essentially an unordered data structure.

As of ES2015 though, the spec guarantees a particular order for objects (number-like, then other strings, then symbols). See [this discussion on StackOverflow](https://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order).

I have a use case where the order of the object properties matters, but currently I cannot control whether the sorting happens or not. I propose adding an option `unorderedObjects`, similar to `unorderedSets` and `unorderedArrays`, true by default.

**Comment by addaleax** [comment]
A PR would be welcome :)
