### ISSUE TITLE
Doesn't support async functions

### ISSUE THREAD

**Issue by wessberg** [puleos/object-hash#67]
Consider:

```javascript
const objectHash = require("object-hash");
objectHash(async function foo () {}); // Error: Unknown object type "asyncfunction"
```

This breaks usage with untranspiled code (node v7.4.0 and above as well as any ES2017+ compatible browser)

I've added a PR: https://github.com/puleos/object-hash/pull/68

**Comment by OZZlE** [comment]
the module is called OBJECT hash, not function hash......

**Comment by wessberg** [comment]
Hi there! I'm not quite sure if you're joking or not, but I'm going to respond to your comment as if you're not.

(1) Are you implying that a function is a primitive value? Rest assured, functions are objects.

(2) If your definition of "object" is actually "object literal" (or "Plain Old JavaScript Object") and what you are saying is that this library should only concern itself with such, please remember that:
    - Object property values can be any type
    - ... Including functions, **which this library already handles**
    - To compute a hash from an object literal, you have to take its' properties into account, wouldn't you say?

If what you are implying is that this library should only compute hashes on object literal, and only based on their identifier, then I must inform you that this library is far more intelligent and wider reaching than that.

In case your comment is a joke, well, here's a beer emoji: 🍺
