### ISSUE TITLE
Add build for <script type="module">

### ISSUE THREAD

**Issue by flyweight** [puleos/object-hash#71]
I'm currently trying to use `import 'object-hash/dist/object_hash.js';` to pull objectHash into my project.  Unfortunately, it throws the following error:

![err](https://i.imgur.com/ZCu0hsl.png)

I created a [jsfiddle](https://jsfiddle.net/yjhdns7p/) that shows the problem.

At a minimum, it would be ideal to resolve the current build issue.  In the future, it would be really helpful if you could support the `.mjs` extension in your build, such as:

https://github.com/pladaria/reconnecting-websocket/blob/master/rollup.config.js#L22

Thanks for your help.

**Comment by addaleax** [comment]
Are you sure this is related to the use of `.mjs`?

Either way, pull requests welcome :)

**Comment by flyweight** [comment]
The problem is currently related to browserify and the node crypto lib.  On 1108, `r = this` and `this = window` within this context.  Unfortunately when using `<script type="module">`, using `this` within its context is undefined.

![crypto](https://i.imgur.com/3RmgqbP.png)

**Comment by flyweight** [comment]
Referencing a similar issue:

https://github.com/aws-amplify/amplify-js/issues/888

**Comment by stuible** [comment]
Experiencing the same problem when building an electron project that uses this project.  For me, Disabling browserfy and using es6 exports before rebuilding the project fixed my issue.

**Comment by blemaire** [comment]
Hi all, just wondering if this is something we can fix? I', working on an old project which get bundled with gulp. In dev mode, this package get imported via a <script> and I get the same error

**Comment by bam-tbf** [comment]
Same here. We want to use a modern and legacy build, but this issue is breaking the modern build strategy that relies on using script type="module".

**Comment by cait08** [comment]
Experiencing the same thing after upgrading my site to Angular 8 (which uses ```script type="module"```. It's a couple months later- is there a fork anyone knows about that supports this?

**Comment by lealceldeiro** [comment]
Any progress on this?

**Comment by addaleax** [comment]
Again, PRs are always welcome. The build system here is quite outdated.

I’ve published `v2.0.1`, let me know if that doesn’t help.

**Comment by stuible** [comment]
I can confirm that my electron project now compiles with the unmodified version of object-hash.  Thank you for your hard work!
