### ISSUE TITLE
Cannot read property 'crypto' of undefined

### ISSUE THREAD

**Issue by baoduy** [puleos/object-hash#76]
I got an error `Cannot read property 'crypto' of undefined` when running on CodeSanbox.
which 'crypto'  package should I install?

**Comment by janek26** [comment]
CodeSandbox ist meant for browser JS, this package requires NodeJS

**Comment by baoduy** [comment]
HI @janek26 
Thanks, I manage to make it work on my project already. Thanks for your help.
