### ISSUE TITLE
Cannot read property 'crypto' of undefined

### ISSUE THREAD

**Issue by jvandyke-dev** [puleos/object-hash#81]
Hey guys, 

I'm getting a 

> Cannot read property 'crypto' of undefined

 error in my Angular/Node.js project written in TypeScript. I looked in object_hash.js:1 and my guess would be it's coming from the line 
`r.crypto&&crypto.getRandomValues`

I'm totally new to Angular and Node and have no idea how to handle this. I've "npm install"-ed both object-hash and @types/object-hash. I've uninstalled and reinstalled. No luck. 

When I open a new folder somewhere else and just try `hash( [1, 'hello world'], { algorithm: 'sha512' })` and logging it to the console, it seems to work just fine. There's no problem in my project until it hits the line `console.log(hash([string1, string2], { algorithm: 'sha512' }));` Any help here?

I should also mention that in a previous non-Angular project, it all worked just fine. I had at the top `import hash from 'object-hash';`, but now I've had to `import * as hash from 'object-hash';` due to a

> Module can only be default-imported using the 'allowSyntheticDefaultImports' flag

error. Please help! This might be a super-simple fix, but I have no idea how to fix this.

**Comment by victorschinaider** [comment]
Same here.

**Comment by antonsimola** [comment]
I have a feeling that this is Angular 8 problem, I started getting this as well after upgrade.

**Comment by tangdiying** [comment]
同样有问题

**Comment by fzxt** [comment]
Not sure. But possibly related. https://github.com/montagejs/collections/issues/162

**Comment by Amerzel** [comment]
Has anyone found a solution to this issue?

**Comment by oniice** [comment]
> I have a feeling that this is Angular 8 problem, I started getting this as well after upgrade.

Same - updated from Angular 6 to 8 and now have this issue

**Comment by sandkampderek** [comment]
Version 2.0.1 fixed this for me: 
https://github.com/puleos/object-hash/commit/1e0835cad7d273b521b8a3beee6c7cb8bd778bee
https://github.com/puleos/object-hash/issues/71

**Comment by jonkoops** [comment]
Closing this issue, as it seems to have been fixed in 2.0.1.
