### ISSUE TITLE
Missing changelog with description of breaking changes

### ISSUE THREAD

**Issue by kachkaev** [puleos/object-hash#87]
Hi @puleos 👋

Thanks for releasing 2.0.0! I was just notified about this release via my tooling, however I could  not find what breaking changes made you release 2.0.0. It'd be great if you could start maintaining `CHANGELOG.md` or add a few sentences on the [Releases page](https://github.com/puleos/object-hash/releases). Knowing what changed is quite handy because upgrading a dependency to a major version may vary from 'doing nothing' to 'refactoring everything' 😅

Examples:
* https://github.com/facebook/react/blob/master/CHANGELOG.md
* https://github.com/facebook/react/releases

**Comment by addaleax** [comment]
There are no breaking changes.

However, unsupported versions of Node.js are no longer being tested in CI. I’ve added a note to the readme file regarding that.
