### ISSUE TITLE
error Error: Unknown object type "promise"

### ISSUE THREAD

**Issue by emahuni** [puleos/object-hash#95]
Module works well unless I pass data that has been resolved from a promise.

```js
error Error: Unknown object type "promise"
    at Object._object (/home/em/project/api/node_modules/object-hash/index.js:223:17)
```

**Comment by ciosoriog** [comment]
Found the same problem, any info?

**Comment by Arsenalist** [comment]
same thing here. no idea what it is.

**Comment by skk2142** [comment]
Just got the same error!! Any updates on this?

**Comment by omar-dulaimi** [comment]
Any explanations?

**Comment by skk2142** [comment]
I moved to using node-object-hash package

**Comment by jaycenhorton** [comment]
[Simple repro](https://replit.com/@jaycenhorton/object-hash-bug-95)

**Comment by addaleax** [comment]
Promises cannot be inspected synchronously, therefore, it is impossible to hash them. You should await your Promises before you pass them to any hashing function at all.

**Comment by emahuni** [comment]
```js
const hasher = require('node-object-hash')();
hasher.hash({ 
  promise: new Promise((resolve) => {
    resolve();
  })
});
```

**Comment by emahuni** [comment]
In that case, the lib should just await promises then hash them once resolved, rather than throw the error.

**Comment by emahuni** [comment]
Use generators.
