### ISSUE TITLE
Object with array of object not working as expected

### ISSUE THREAD

**Issue by dilipsarkar** [puleos/object-hash#96]
Hi,
I'm trying to generate an Object hash which again includes an array of Object. What seems to be happening is if the value of an array of object element changes, it still returns the same object hash. But adding/removing elements from the array of object seems to be working fine. Is this something expected ? My implementation details below - 

```
  private getHash(filter: SearchFilter) {
    return objectHash(filter, {
      excludeKeys(key: string) {
        if (key === 'filterCriteria' || key === 'sortCriteria') {
          return false;
        }
        return true;
      },
      respectType: true
    });
  }
```

Sample input/output:

1. Test one

 Input => _{"pageSize":48,"pageNumber":1,"filterCriterias":[],"sortCriterias":[{"sortColumn":"NeedByDate","sortOrder":"asc"},{"sortColumn":"Status","sortOrder":"asc"}]}_

Output object hash => _**535c3001aaae9307daae192e1467b64126937576**_

2. Test two
Input => _{"pageSize":8,"pageNumber":1,"filterCriterias":[],"sortCriterias":[{"sortColumn":"NeedByDate","sortOrder":"desc"},{"sortColumn":"Status","sortOrder":"asc"}]}_ 

Output object hash => _**535c3001aaae9307daae192e1467b64126937576**_

Thanks,
Dilip

**Comment by addaleax** [comment]
Is one of the `return true;`s in the `excludeKeys` function supposed to be a `return false;`? :)

**Comment by dilipsarkar** [comment]
Sorry, I was trying multiple things, so the copied getHash method code was wrong. I have updated it and double check as well. Issue seems to be genuine

**Comment by addaleax** [comment]
@dilipsarkar There is a mismatch between the names in the code – the `excludeKeys` function uses `filterCriteria` and `sortCriteria`, the objects themselves use `filterCriterias` and `sortCriterias` (with an extra `s` at the end).

(Just in case you’re curious – the word is borrowed from Ancient Greek, so “criterion” is the singular and “criteria” is the plural, “criterias” is not really a thing in English :slightly_smiling_face:)

**Comment by dilipsarkar** [comment]
Thanks @addaleax 
I think what you have pointed out is one part of the issue, with that rectified also it wasn't working as expected. Actually inside excludeKeys, I wanted to include keys only for `filterCriterias` and `sortCriteria` so I was returning true when those keys were matched. When I changed my implementation otherwise i.e. skip `pageNumber` and `pageSize`(code below), it seems to be working fine. It doesn’t look very convincing to me but that seems to be working.

```
private getHash(filter: SearchFilter) {
    return objectHash(filter, {
      excludeKeys(key: string) {
        if (key === 'pageNumber' || key === 'pageSize') {
          return true;
        }
        return false;
      }
    });
  }
```

Appreciate your help and also thanks for the additional information on "criteria", wasn’t aware of it. Will make the necessary changes according :)

**Comment by addaleax** [comment]
@dilipsarkar Okay, great to hear that worked out for you! Sounds like the code does what you intend it to do :+1:
